# Generated by Django 5.2.8 on 2025-12-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_items',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
