# Generated by Django 5.2.8 on 2025-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0004_alter_shop_items_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_items',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
