# Generated by Django 5.2.8 on 2025-12-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0007_alter_cart_cart_status_alter_cart_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_items',
            name='note',
        ),
    ]
