# Generated by Django 5.2.8 on 2025-12-22 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0008_remove_shop_items_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_owner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shop_owner',
            name='password',
        ),
        migrations.AddField(
            model_name='shop_owner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
