# Generated by Django 5.2.8 on 2025-12-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0009_remove_shop_owner_email_remove_shop_owner_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_info',
            name='script_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
