# Generated by Django 5.2.8 on 2025-12-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0010_shop_info_script_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
