# Generated by Django 5.2.8 on 2025-12-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0011_cart_items_is_printed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
    ]
