# Generated by Django 6.0.1 on 2026-02-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0012_rename_user_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_info',
            name='close_time',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='shop_info',
            name='open_time',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='shop_info',
            name='open_weekdays',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
