# Generated by Django 6.0.1 on 2026-02-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0013_shop_info_close_time_shop_info_open_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
