# Generated by Django 6.0.1 on 2026-02-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0014_alter_cart_pickup_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_info',
            name='status',
            field=models.CharField(default='Active', max_length=255),
        ),
    ]
