# Generated by Django 6.0.1 on 2026-02-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0015_shop_info_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_pages',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
