# Generated by Django 6.0.1 on 2026-02-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0016_cart_total_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
    ]
