# Generated by Django 6.0.1 on 2026-02-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0017_alter_cart_total_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_info',
            name='close_time',
            field=models.CharField(default='17:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='shop_info',
            name='open_time',
            field=models.CharField(default='10:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='shop_info',
            name='open_weekdays',
            field=models.CharField(default='0123456', max_length=7),
        ),
    ]
