# Generated by Django 6.0.1 on 2026-02-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0018_alter_shop_info_close_time_alter_shop_info_open_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_info',
            name='close_time',
            field=models.TimeField(default='17:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='shop_info',
            name='open_time',
            field=models.TimeField(default='10:00', max_length=5),
        ),
    ]
