# Generated by Django 6.0.1 on 2026-02-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0019_alter_shop_info_close_time_alter_shop_info_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
