# Generated by Django 6.0.1 on 2026-02-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0020_cart_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_verified',
        ),
    ]
