# Generated by Django 6.0.1 on 2026-02-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0021_remove_cart_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='is_cleaned',
            field=models.BooleanField(default=False),
        ),
    ]
