# Generated by Django 6.0.1 on 2026-03-29 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0024_alter_feedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_info',
            name='close_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AlterField(
            model_name='shop_info',
            name='open_time',
            field=models.TimeField(default='10:00'),
        ),
        migrations.CreateModel(
            name='Shop_timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='printoapp.shop_info')),
            ],
        ),
    ]
