# Generated by Django 6.0.1 on 2026-03-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0025_alter_shop_info_close_time_alter_shop_info_open_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_info',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='shop_info',
            name='open_time',
        ),
        migrations.RemoveField(
            model_name='shop_info',
            name='open_weekdays',
        ),
    ]
