# Generated by Django 6.0.1 on 2026-04-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0026_remove_shop_info_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='upload_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
