# Generated by Django 6.0.1 on 2026-04-12 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0027_cart_items_upload_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='upload_timestamp',
        ),
    ]
