# Generated by Django 6.0.1 on 2026-04-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0028_remove_cart_items_upload_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_status',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
