# Generated by Django 6.0.1 on 2026-04-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0029_remove_cart_cart_status_cart_is_open_cart_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='cart_items',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop_items',
            name='platform_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='shop_items',
            name='shop_percent',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Cart_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('shop_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('platform_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('platform_charges_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=3)),
                ('payment_gateway_percent', models.DecimalField(decimal_places=2, default=2.0, max_digits=3)),
                ('payment_gateway_gst_percent', models.DecimalField(decimal_places=2, default=18.0, max_digits=3)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_total', to='printoapp.cart')),
            ],
        ),
    ]
