# Generated by Django 6.0.1 on 2026-04-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0030_remove_cart_total_amount_cart_items_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_total',
            name='payment_gateway_gst_percent',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cart_total',
            name='payment_gateway_percent',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cart_total',
            name='platform_charges_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
