# Generated by Django 6.0.1 on 2026-04-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0031_alter_cart_total_payment_gateway_gst_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
