# Generated by Django 6.0.1 on 2026-04-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0032_remove_cart_updated_at_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_total',
            name='priority_percent',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=9),
        ),
    ]
