# Generated by Django 6.0.4 on 2026-04-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0034_cart_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_cleaned',
            field=models.BooleanField(default=False),
        ),
    ]
