# Generated by Django 6.0.4 on 2026-04-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0035_cart_is_cleaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
