# Generated by Django 5.2.13 on 2026-04-26 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0036_cart_is_printed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pickup_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='printoapp.cart'),
        ),
    ]
