# Generated by Django 5.2.13 on 2026-05-04 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0037_alter_cart_pickup_code_alter_cart_items_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('discount_percent', models.IntegerField(default=0)),
                ('max_use', models.IntegerField(blank=True, null=True)),
                ('days_valid', models.IntegerField(blank=True, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min_cart_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='printoapp.shop_info')),
            ],
        ),
    ]
