# Generated by Django 5.2.13 on 2026-05-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0038_shop_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='raw_pages_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
