# Generated by Django 5.2.13 on 2026-05-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0039_cart_items_raw_pages_count_alter_feedback_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='requires_scaling',
            field=models.BooleanField(default=False),
        ),
    ]
