# Generated by Django 5.2.13 on 2026-05-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0040_cart_items_requires_scaling'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='is_portrait',
            field=models.BooleanField(default=True),
        ),
    ]
