# Generated by Django 5.2.13 on 2026-05-08 13:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0042_feedback_shop_admin_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_data',
            new_name='Admin_dash',
        ),
    ]
