# Generated by Django 5.2.13 on 2026-05-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0043_rename_admin_data_admin_dash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='is_portrait',
        ),
    ]
