# Generated by Django 5.2.13 on 2026-05-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0044_remove_cart_items_is_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_items',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
