# Generated by Django 5.2.13 on 2026-05-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0045_shop_items_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_items',
            name='is_active',
        ),
    ]
