# Generated by Django 5.2.13 on 2026-05-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0046_remove_shop_items_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_total',
            name='platform_charges_percent',
        ),
        migrations.RemoveField(
            model_name='shop_items',
            name='platform_percent',
        ),
        migrations.RemoveField(
            model_name='shop_items',
            name='shop_percent',
        ),
        migrations.AddField(
            model_name='shop_items',
            name='platform_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
