# Generated by Django 5.2.13 on 2026-05-13 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0047_remove_cart_total_platform_charges_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_info',
            name='gst_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shop_info',
            name='sub_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_owner',
            name='IFSC_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shop_owner',
            name='account_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shop_owner',
            name='account_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shop_owner',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='shop_owner',
            name='nickname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shop_owner',
            name='payee_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Settlements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sett_id', models.CharField(max_length=255)),
                ('sett_time', models.DateTimeField()),
                ('sett_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin', to='printoapp.admin_dash')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='printoapp.shop_info')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_time', models.DateTimeField()),
                ('trans_money', models.DecimalField(decimal_places=2, max_digits=9)),
                ('trans_id', models.CharField(max_length=255)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='printoapp.shop_info')),
            ],
        ),
    ]
