# Generated by Django 5.2.13 on 2026-05-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0048_shop_info_gst_number_shop_info_sub_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_total',
            name='otp_page_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart_total',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
    ]
