# Generated by Django 5.2.13 on 2026-05-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0049_cart_total_otp_page_discount_cart_total_total_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_total',
            name='round_up',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
