# Generated by Django 5.2.13 on 2026-05-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0050_cart_total_round_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_total',
            name='otp_page_discount',
        ),
        migrations.AddField(
            model_name='cart_total',
            name='payment_gateway_total_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cart_total',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cart_total',
            name='priority_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cart_total',
            name='raw_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
