# Generated by Django 5.2.13 on 2026-05-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0052_feedback_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlements',
            name='admin',
        ),
    ]
