# Generated by Django 5.2.13 on 2026-06-13 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0053_remove_settlements_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fp_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(max_length=255)),
                ('refund_amount', models.IntegerField()),
                ('refund_status', models.CharField(max_length=56)),
                ('refund_speed', models.CharField(max_length=56)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='printoapp.cart')),
            ],
        ),
    ]
