# Generated by Django 5.2.13 on 2026-06-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0054_cart_fp_timestamp_cart_is_refunded_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_refunded',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
