# Generated by Django 5.2.13 on 2026-07-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printoapp', '0055_remove_cart_is_refunded_delete_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='is_long_edge',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart_items',
            name='is_portrait',
            field=models.BooleanField(default=True),
        ),
    ]
